name: ci/cd

on:
  push:
    branches: ['main', 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: ['main', 'release/**', 'task/**', 'feature/**', 'epic/**']
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install deps
      run: sudo apt-get install libasound2-dev
    - name: Get current directory
      run: |
        pwd
        ls -al
    - name: Build
      run: go build -v -race ./...
    - name: Test
      run: go test -v -race ./...
