name: binary release builder

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cross-compile midiserver
        uses: ut-proj/midiserver/builder@main
        with:
          args: ${{ matrix.goos }}/${{ matrix.goarch }}
