name: binary release builder

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/midiserver"
          binary_name: "midiserver"
          asset_name: "midiserver-${{ matrix.goos }}-${{ matrix.goarch }}"
          pre_command: "apt-get install libasound2-dev libsndfile-dev"
          build_command: "make ${{ matrix.goos }}"
