name: midiserver release builders

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  linux-amd64-release:
    name: Linux AMD64 Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Linux midiserver
        uses: ut-proj/midiserver/builder@main
        with:
          args: ${{ matrix.goos }}/${{ matrix.goarch }}
      - name: Release Linux midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: builds/midiserver-linux-amd64
  darwin-releases:
    name: MacOS Go binaries
    runs-on: macos-11
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build
        run: |
          make
          mv bin/midiserver bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Release macOS midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}