name: binary release builder

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:  
          - goarch: arm64
            goos: windows 
    steps:
      - name: Install deps
        run: sudo apt-get install libasound2-dev libsndfile-dev
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/midiserver"
          binary_name: "midiserver"
          pre_command: "sudo apt-get install libasound2-dev libsndfile-dev"
          build_command: "make"
