name: midiserver release builders

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  linux-amd64-release:
    name: Linux AMD64 Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Linux midiserver
        uses: ut-proj/midiserver/builder@main
        with:
          args: ${{ matrix.goos }}/${{ matrix.goarch }}
      - name: Release Linux midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: builds/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}
  darwin-amd64-releases:
    name: MacOS AMD64 Go binary
    runs-on: macos-11
    strategy:
      matrix:
        goos: [darwin]
        goarch: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build
        run: |
          make
          ls -al bin/
      - name: Release macOS midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}
  darwin-arm64-releases:
    name: MacOS ARM64 Go binary
    runs-on: macos-11
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release macOS midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}
  linux-arm64-releases:
    name: Linux ARM64 Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Linux midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}
  linux-armv7l-releases:
    name: Linux/Raspberry PI Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [armv7l]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Linux/Raspberry midiserver
        uses: softprops/action-gh-release@v1
        with:
          files: bin/midiserver-${{ matrix.goos }}-${{ matrix.goarch }}

